/*
 * TidePlugin.java
 * Copyright (c) 2002 Paul Dana
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 */

package com.garagegames.torque.tide;

import java.io.File;
import java.io.IOException;
import java.util.Vector;
import javax.swing.*;

import org.gjt.sp.jedit.*;
import org.gjt.sp.jedit.msg.EditPaneUpdate;
import org.gjt.sp.jedit.msg.ViewUpdate;
import org.gjt.sp.jedit.textarea.JEditTextArea;
import org.gjt.sp.util.Log;

public class TidePlugin extends EBPlugin
{
   // the current alpha test information property
   public static final String SeenTestInfoProperty =
      "plugin.com.garagegames.torque.tide.TidePlugin.seenAlphaTestInfo_021";

   protected JMenu tideMenu;
   protected Tide tide;

   /**
    * The menu property for this plugin
    */
   //public static final String MENU = "tide.menu";
   public static final String MENU = "plugin.com.garagegames.torque.tide.TidePlugin.menu";


   public void start()
   {
      /*
      if(!MiscUtilities.isToolsJarAvailable())
      {
      // I can't live without my tools.jar:
      throw new UnsupportedOperationException(
      "Could not find library tools.jar!\n"
      + "This library is essential for running the Debugger plugin.\n"
      + "It usually resides in {java.home}/lib/.\n"
      + "Your java.home is " + System.getProperty("java.home") + "\n"
      + "A common cause of this error is that jEdit was\n"
      + "launched through a JRE instead of a JDK.\n"
      + "It doesn't help to add it to the CLASSPATH.\n"
      + "Try adding it to jEdit's jars/ folder.");
   }
      */
      tide = Tide.createTide(this);
   }

   public void stop()
   {
   }


   /**
    * Handle messages allows us to respond to particular messages generated by
    * jEdit and send on the EditBus.
    **/
   public void handleMessage(EBMessage message)
   {
      if (message instanceof ViewUpdate)
      {
         // on first view load display alpha testing information
         ViewUpdate vmsg = (ViewUpdate) message;
         if (vmsg.getWhat() == ViewUpdate.CREATED)
         {
            // if we have seen this before...do nothing
            String seen = jEdit.getProperty(SeenTestInfoProperty);
            if (seen == null)
            {
               jEdit.setProperty(SeenTestInfoProperty,"true");
               Tide.displayAlphaTestingInfo(vmsg.getView());
            }
         }
      }
   }

   // expose this to Tide
   public JMenu getTideMenu()
   {
      return tideMenu;
   }
}


